db = dofile('./libs/redis.lua')
io.write("ایدی تبچی را وارد کنید : ")
local last = io.read()
io.write("\nایدی عددی سودو را وارد کنید : ")
local admin=io.read()
io.open("jovetab-"..last..".lua",'w'):write("\nfunction reload()\n\njovetab = dofile('jovetab.lua')\nend\nreload()"):close()
io.open("jovetab-"..last..".sh",'w'):write("while true; do\n$(dirname $0)/tg -p jovetab-"..last.." -s jovetab-"..last..".lua\ndone"):close()
io.popen("chmod 777 jovetab-"..last..".sh")
db:sadd('bot'..last..'admin', admin)
print("ایدی سودو:"..admin.."")